name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
      imageName:
        required: true
        type: string
      digest:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying ${{ inputs.imageName }} with digest ${{ inputs.digest }}. Environment variable ${{ vars.WORKSHOP_ENV_VARIABLE }}"
