name: Build and test

on:
  - pull_request
  - workflow_dispatch

jobs:
  test:
    uses: ./.github/workflows/reusable.test.yml
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Verify formatting
        run: |
          no_unformatted_files="$(gofmt -l $(git ls-files '*.go') | wc -l)"
          exit "$no_unformatted_files"
